#!/bin/bash
# ref: https://github.com/davidecavestro/mariadb-docker-armhf/tree/756c3f31a117341896c37976640055fb43d5b004
# ref: https://github.com/docker/hub-feedback/issues/1261
# uname -a
# cat /proc/sys/fs/binfmt_misc/qemu-arm
# apt-get update
# apt-get install -y curl qemu-user-static binfmt-support
# cat /proc/sys/fs/binfmt_misc/qemu-arm
## local copy of qemu binary 
# cp -p $(which qemu-arm-static) .
## downloads a local copy of qemu on docker-hub build machines
# curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .

cp bin/qemu-aarch64-static .
